# fly.toml app configuration file generated for ppb on 2025-05-03T23:02:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ppb'
primary_region = 'den'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
