app = "colorado-plumbers-guild"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "300s"
    interval = "60s"
    method = "GET"
    timeout = "30s"
    path = "/health"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
  
# Tune startup performance  
[deploy]
  strategy = "immediate"
  release_command = "python -c 'import time; time.sleep(5)'"
